ci:
  autoupdate_schedule: quarterly
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        # "In Python 3.11 and newer, the class syntax supports generic named tuple classes."
        # https://typing.readthedocs.io/en/latest/spec/namedtuples.html
        language_version: "3.11"
        exclude: "(docs|tests)/"
        additional_dependencies:
          - types-orjson
          - types-pika
