[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 119

[tool.isort]
profile = 'black'
line_length = 119

[tool.pydocstyle]
match_dir = '(?!tests).*'
ignore = 'D100,D104,D200,D203,D205,D212,D400,D415'

[tool.ruff]
line-length = 119
select = ["ALL"]
ignore = ["ANN", "COM", "EM", "D100", "D104", "D200", "D203", "D205", "D212", "D400", "D415"]
target-version = "py310"

[tool.ruff.per-file-ignores]
"tests/*" = [
  "D",  # docstring
  "ARG001",  # unused pytest fixture
  "FBT003",  # boolean positional value
  "PLR2004", # unnamed constant value
  "S101",  # assert
]

[tool.ruff.flake8-builtins]
builtins-ignorelist = ["copyright"]
