name: CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # https://github.com/pika/pika/issues/1479
        python-version: ['3.10', '3.11']  # '3.12', '3.13'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml
      - run: pip install .[test]
      # Python 3.10 issues "DeprecationWarning: There is no current event loop" spuriously
      - if: matrix.python-version == '3.10'
        name: Test
        env:
          TEST_RABBIT_URL: amqp://127.0.0.1:${{ job.services.rabbitmq.ports[5672] }}
        shell: bash
        run: |
          coverage run --source=yapw --append -m pytest
          pip install orjson
          coverage run --source=yapw --append -m pytest
          pip uninstall -y orjson
      - if: matrix.python-version != '3.10'
        name: Test
        env:
          TEST_RABBIT_URL: amqp://127.0.0.1:${{ job.services.rabbitmq.ports[5672] }}
        shell: bash
        run: |
          coverage run --source=yapw --append -m pytest -W error -W ignore::ResourceWarning
          pip install orjson
          coverage run --source=yapw --append -m pytest -W error -W ignore::ResourceWarning
          pip uninstall -y orjson
      - uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
    services:
      rabbitmq:
        image: rabbitmq:latest
        options: >-
          --health-cmd "rabbitmq-diagnostics -q check_running"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5672/tcp
